# Pandas Basic - 3

YT Video Ref: <br/>
**[Complete Python Pandas Data Science Tutorial! (Reading CSV/Excel files, Sorting, Filtering, Groupby)](https://www.youtube.com/watch?v=vmEHCJofslg&t=1s)**


#### Dataset is stored in the following path

**"C:\Users\Creative IT\Jupyter Notebooks\DataSets\Pandas Basics (Keith Galli)\pandas-master"**

**Agenda**
+ Reading CSV, Excel, Text files
+ Sorting Data
+ Filtering Data
+ Groupby Data

Ref for completing the documentation
+ [**JournalDev - df.loc[]**](https://www.journaldev.com/36384/pandas-dataframe-loc)
+ [**geeksforgeeks - df.sort_values()**](https://www.geeksforgeeks.org/python-pandas-dataframe-sort_values-set-1/)
+ [**geeksforgeeks - df.groupby()**](https://www.geeksforgeeks.org/python-pandas-dataframe-groupby/)
+ [**Data Science Parichay - Count after groupby**](https://datascienceparichay.com/article/pandas-groupby-count-of-rows-in-each-group/)

In [1]:
# import required libraries
import pandas as pd

### Load the file

Loading Types
+ Load CSV files
+ Load Excel files
+ Load txt files

In [2]:
# Loading type-1: Load CSV file
data_csv = pd.read_csv("../DataSets/Pandas Basics (Keith Galli)/pandas-master/pokemon_data.csv")
data_csv.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [3]:
data_csv.shape

(800, 12)

In [4]:
# The overview information of the dataframe
data_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

In [5]:
# Loading type-2: Load Excel file
data_excel = pd.read_excel("../DataSets/Pandas Basics (Keith Galli)/pandas-master/pokemon_data.xlsx")
data_excel.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [6]:
data_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

[ **Note** ] If the dataset is in the "txt" format, then most probably the contents will be tab/comma-separated. Thus while reading the dataset using the **df.read_csv()** func from pandas-library, we should define the "**delimiter**" attribute.

**"Delimiter" meaning**: A character that marks the beginning or end of a unit of data.

In [7]:
# Loading type-3: Load txt file (using the df.read_csv() function)
data_txt = pd.read_csv("../DataSets/Pandas Basics (Keith Galli)/pandas-master/pokemon_data.txt", delimiter="\t")
print(data_txt.head())

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [8]:
data_txt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

### Read the different parts of the dataframe

+ Read the column names (headers) of the dataframe.
+ Read values of any particular column.
    + Type-1: Column name inside the quatation; then cover with sqaure-brackets.
    + Type-2: Define the columnName following the dot (".") of the dataframe name.
+ Display values of a list of particular columns.
+ Display the first 8 rows of the dataframe using the "df.head()" function.
+ Experience more control using the "df.loc[]" & "df.iloc[]" function.
    + "df.loc[row, columnLabel]" function: It works with only labels while defining columns.
    + "df.iloc[row, columnLabel]"function: It works with only the index-values of both rows & columns.

In [9]:
# Read the header (ColumnNames) of the dataframe
print(data_csv.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [10]:
# Read values of any particular column; "Name" column
data_csv["Name"]

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [11]:
data_csv.Name

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [12]:
# Read values of a list of particular columns; ["Name", "Type 1", "Type 2", "HP"] columns
data_csv[["Name", "Type 1", "Type 2", "HP"]]

                      Name   Type 1  Type 2  HP
0                Bulbasaur    Grass  Poison  45
1                  Ivysaur    Grass  Poison  60
2                 Venusaur    Grass  Poison  80
3    VenusaurMega Venusaur    Grass  Poison  80
4               Charmander     Fire     NaN  39
..                     ...      ...     ...  ..
795                Diancie     Rock   Fairy  50
796    DiancieMega Diancie     Rock   Fairy  50
797    HoopaHoopa Confined  Psychic   Ghost  80
798     HoopaHoopa Unbound  Psychic    Dark  80
799              Volcanion     Fire   Water  80

[800 rows x 4 columns]

In [13]:
# Display the first 8 rows using the "df.head()" func
data_csv.head(8)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False

In [14]:
# Use the "df.loc[]" function; rows=8; columns=first 6;
# While defining rows, define numeric values while defining the slice as considering it as a python-list-slicing
# While defining columns, cover it with sqaure-brackets for defining multiple columns. But each column-name will be single/double quatationed inside the brackets.
data_csv.loc[0:8, ["Name", "Type 1", "Type 2", "HP", "Attack", "Defense"]]

                        Name Type 1  Type 2  HP  Attack  Defense
0                  Bulbasaur  Grass  Poison  45      49       49
1                    Ivysaur  Grass  Poison  60      62       63
2                   Venusaur  Grass  Poison  80      82       83
3      VenusaurMega Venusaur  Grass  Poison  80     100      123
4                 Charmander   Fire     NaN  39      52       43
5                 Charmeleon   Fire     NaN  58      64       58
6                  Charizard   Fire  Flying  78      84       78
7  CharizardMega Charizard X   Fire  Dragon  78     130      111
8  CharizardMega Charizard Y   Fire  Flying  78     104       78

In [15]:
# Use the "df.iloc[]" function; rows=8; columns=first 6;
# While defining both the rows & columns; we can use the index-values (index+1)
data_csv.iloc[:9, :7]

   #                       Name Type 1  Type 2  HP  Attack  Defense
0  1                  Bulbasaur  Grass  Poison  45      49       49
1  2                    Ivysaur  Grass  Poison  60      62       63
2  3                   Venusaur  Grass  Poison  80      82       83
3  3      VenusaurMega Venusaur  Grass  Poison  80     100      123
4  4                 Charmander   Fire     NaN  39      52       43
5  5                 Charmeleon   Fire     NaN  58      64       58
6  6                  Charizard   Fire  Flying  78      84       78
7  6  CharizardMega Charizard X   Fire  Dragon  78     130      111
8  6  CharizardMega Charizard Y   Fire  Flying  78     104       78

### "df.iterrows()" function
Syntax: **df.iterrows(index, Series)**
> Definition: **Iterate over DataFrame rows as (index, Series) pairs.** <br/>
**index**: The index of each dataframe row. <br/>
**Series**: Specific data-column in both formats ("square-brackets" & "dot-format").

In [16]:
for index, row in data_csv.iterrows():
    print(index, "--------", row.Name)

0 -------- Bulbasaur
1 -------- Ivysaur
2 -------- Venusaur
3 -------- VenusaurMega Venusaur
4 -------- Charmander
5 -------- Charmeleon
6 -------- Charizard
7 -------- CharizardMega Charizard X
8 -------- CharizardMega Charizard Y
9 -------- Squirtle
10 -------- Wartortle
11 -------- Blastoise
12 -------- BlastoiseMega Blastoise
13 -------- Caterpie
14 -------- Metapod
15 -------- Butterfree
16 -------- Weedle
17 -------- Kakuna
18 -------- Beedrill
19 -------- BeedrillMega Beedrill
20 -------- Pidgey
21 -------- Pidgeotto
22 -------- Pidgeot
23 -------- PidgeotMega Pidgeot
24 -------- Rattata
25 -------- Raticate
26 -------- Spearow
27 -------- Fearow
28 -------- Ekans
29 -------- Arbok
30 -------- Pikachu
31 -------- Raichu
32 -------- Sandshrew
33 -------- Sandslash
34 -------- Nidoran (Female)
35 -------- Nidorina
36 -------- Nidoqueen
37 -------- Nidoran (Male)
38 -------- Nidorino
39 -------- Nidoking
40 -------- Clefairy
41 -------- Clefable
42 -------- Vulpix
43 -------- Ninetales
44 -------- Jigglypuff
45 -------- Wigglytuff
46 -------- Zubat
47 -------- Golbat
48 -------- Oddish
49 -------- Gloom
50 -------- Vileplume
51 -------- Paras
52 -------- Parasect
53 -------- Venonat
54 -------- Venomoth
55 -------- Diglett
56 -------- Dugtrio
57 -------- Meowth
58 -------- Persian
59 -------- Psyduck
60 -------- Golduck
61 -------- Mankey
62 -------- Primeape
63 -------- Growlithe
64 -------- Arcanine
65 -------- Poliwag
66 -------- Poliwhirl
67 -------- Poliwrath
68 -------- Abra
69 -------- Kadabra
70 -------- Alakazam
71 -------- AlakazamMega Alakazam
72 -------- Machop
73 -------- Machoke
74 -------- Machamp
75 -------- Bellsprout
76 -------- Weepinbell
77 -------- Victreebel
78 -------- Tentacool
79 -------- Tentacruel
80 -------- Geodude
81 -------- Graveler
82 -------- Golem
83 -------- Ponyta
84 -------- Rapidash
85 -------- Slowpoke
86 -------- Slowbro
87 -------- SlowbroMega Slowbro
88 -------- Magnemite
89 -------- Magneton
90 -------- Farfetch'd
91 -------- Doduo
92 -------- Dodrio
93 -------- Seel
94 -------- Dewgong
95 -------- Grimer
96 -------- Muk
97 -------- Shellder
98 -------- Cloyster
99 -------- Gastly
100 -------- Haunter
101 -------- Gengar
102 -------- GengarMega Gengar
103 -------- Onix
104 -------- Drowzee
105 -------- Hypno
106 -------- Krabby
107 -------- Kingler
108 -------- Voltorb
109 -------- Electrode
110 -------- Exeggcute
111 -------- Exeggutor
112 -------- Cubone
113 -------- Marowak
114 -------- Hitmonlee
115 -------- Hitmonchan
116 -------- Lickitung
117 -------- Koffing
118 -------- Weezing
119 -------- Rhyhorn
120 -------- Rhydon
121 -------- Chansey
122 -------- Tangela
123 -------- Kangaskhan
124 -------- KangaskhanMega Kangaskhan
125 -------- Horsea
126 -------- Seadra
127 -------- Goldeen
128 -------- Seaking
129 -------- Staryu
130 -------- Starmie
131 -------- Mr. Mime
132 -------- Scyther
133 -------- Jynx
134 -------- Electabuzz
135 -------- Magmar
136 -------- Pinsir
137 -------- PinsirMega Pinsir
138 -------- Tauros
139 -------- Magikarp
140 -------- Gyarados
141 -------- GyaradosMega Gyarados
142 -------- Lapras
143 -------- Ditto
144 -------- Eevee
145 -------- Vaporeon
146 -------- Jolteon
147 -------- Flareon
148 -------- Porygon
149 -------- Omanyte
150 -------- Omastar
151 -------- Kabuto
152 -------- Kabutops
153 -------- Aerodactyl
154 -------- AerodactylMega Aerodactyl
155 -------- Snorlax
156 -------- Articuno
157 -------- Zapdos
158 -------- Moltres
159 -------- Dratini
160 -------- Dragonair
161 -------- Dragonite
162 -------- Mewtwo
163 -------- MewtwoMega Mewtwo X
164 -------- MewtwoMega Mewtwo Y
165 -------- Mew
166 -------- Chikorita
167 -------- Bayleef
168 -------- Meganium
169 -------- Cyndaquil
170 -------- Quilava
171 -------- Typhlosion
172 -------- Totodile
173 -------- Croconaw
174 -------- Feraligatr
175 -------- Sentret
176 -------- Furret
177 -------- Hoothoot
178 -------- Noctowl
179 -------- Ledyba
180 -------- Ledian
181 -------- Spinarak
182 -------- Ariados
183 -------- Crobat
184 -------- Chinchou
185 -------- Lanturn
186 -------- Pichu
187 -------- Cleffa
188 -------- Igglybuff
189 -------- Togepi
190 -------- Togetic
191 -------- Natu
192 -------- Xatu
193 -------- Mareep
194 -------- Flaaffy
195 -------- Ampharos
196 -------- AmpharosMega Ampharos
197 -------- Bellossom
198 -------- Marill
199 -------- Azumarill
200 -------- Sudowoodo
201 -------- Politoed
202 -------- Hoppip
203 -------- Skiploom
204 -------- Jumpluff
205 -------- Aipom
206 -------- Sunkern
207 -------- Sunflora
208 -------- Yanma
209 -------- Wooper
210 -------- Quagsire
211 -------- Espeon
212 -------- Umbreon
213 -------- Murkrow
214 -------- Slowking
215 -------- Misdreavus
216 -------- Unown
217 -------- Wobbuffet
218 -------- Girafarig
219 -------- Pineco
220 -------- Forretress
221 -------- Dunsparce
222 -------- Gligar
223 -------- Steelix
224 -------- SteelixMega Steelix
225 -------- Snubbull
226 -------- Granbull
227 -------- Qwilfish
228 -------- Scizor
229 -------- ScizorMega Scizor
230 -------- Shuckle
231 -------- Heracross
232 -------- HeracrossMega Heracross
233 -------- Sneasel
234 -------- Teddiursa
235 -------- Ursaring
236 -------- Slugma
237 -------- Magcargo
238 -------- Swinub
239 -------- Piloswine
240 -------- Corsola
241 -------- Remoraid
242 -------- Octillery
243 -------- Delibird
244 -------- Mantine
245 -------- Skarmory
246 -------- Houndour
247 -------- Houndoom
248 -------- HoundoomMega Houndoom
249 -------- Kingdra
250 -------- Phanpy
251 -------- Donphan
252 -------- Porygon2
253 -------- Stantler
254 -------- Smeargle
255 -------- Tyrogue
256 -------- Hitmontop
257 -------- Smoochum
258 -------- Elekid
259 -------- Magby
260 -------- Miltank
261 -------- Blissey
262 -------- Raikou
263 -------- Entei
264 -------- Suicune
265 -------- Larvitar
266 -------- Pupitar
267 -------- Tyranitar
268 -------- TyranitarMega Tyranitar
269 -------- Lugia
270 -------- Ho-oh
271 -------- Celebi
272 -------- Treecko
273 -------- Grovyle
274 -------- Sceptile
275 -------- SceptileMega Sceptile
276 -------- Torchic
277 -------- Combusken
278 -------- Blaziken
279 -------- BlazikenMega Blaziken
280 -------- Mudkip
281 -------- Marshtomp
282 -------- Swampert
283 -------- SwampertMega Swampert
284 -------- Poochyena
285 -------- Mightyena
286 -------- Zigzagoon
287 -------- Linoone
288 -------- Wurmple
289 -------- Silcoon
290 -------- Beautifly
291 -------- Cascoon
292 -------- Dustox
293 -------- Lotad
294 -------- Lombre
295 -------- Ludicolo
296 -------- Seedot
297 -------- Nuzleaf
298 -------- Shiftry
299 -------- Taillow
300 -------- Swellow
301 -------- Wingull
302 -------- Pelipper
303 -------- Ralts
304 -------- Kirlia
305 -------- Gardevoir
306 -------- GardevoirMega Gardevoir
307 -------- Surskit
308 -------- Masquerain
309 -------- Shroomish
310 -------- Breloom
311 -------- Slakoth
312 -------- Vigoroth
313 -------- Slaking
314 -------- Nincada
315 -------- Ninjask
316 -------- Shedinja
317 -------- Whismur
318 -------- Loudred
319 -------- Exploud
320 -------- Makuhita
321 -------- Hariyama
322 -------- Azurill
323 -------- Nosepass
324 -------- Skitty
325 -------- Delcatty
326 -------- Sableye
327 -------- SableyeMega Sableye
328 -------- Mawile
329 -------- MawileMega Mawile
330 -------- Aron
331 -------- Lairon
332 -------- Aggron
333 -------- AggronMega Aggron
334 -------- Meditite
335 -------- Medicham
336 -------- MedichamMega Medicham
337 -------- Electrike
338 -------- Manectric
339 -------- ManectricMega Manectric
340 -------- Plusle
341 -------- Minun
342 -------- Volbeat
343 -------- Illumise
344 -------- Roselia
345 -------- Gulpin
346 -------- Swalot
347 -------- Carvanha
348 -------- Sharpedo
349 -------- SharpedoMega Sharpedo
350 -------- Wailmer
351 -------- Wailord
352 -------- Numel
353 -------- Camerupt
354 -------- CameruptMega Camerupt
355 -------- Torkoal
356 -------- Spoink
357 -------- Grumpig
358 -------- Spinda
359 -------- Trapinch
360 -------- Vibrava
361 -------- Flygon
362 -------- Cacnea
363 -------- Cacturne
364 -------- Swablu
365 -------- Altaria
366 -------- AltariaMega Altaria
367 -------- Zangoose
368 -------- Seviper
369 -------- Lunatone
370 -------- Solrock
371 -------- Barboach
372 -------- Whiscash
373 -------- Corphish
374 -------- Crawdaunt
375 -------- Baltoy
376 -------- Claydol
377 -------- Lileep
378 -------- Cradily
379 -------- Anorith
380 -------- Armaldo
381 -------- Feebas
382 -------- Milotic
383 -------- Castform
384 -------- Kecleon
385 -------- Shuppet
386 -------- Banette
387 -------- BanetteMega Banette
388 -------- Duskull
389 -------- Dusclops
390 -------- Tropius
391 -------- Chimecho
392 -------- Absol
393 -------- AbsolMega Absol
394 -------- Wynaut
395 -------- Snorunt
396 -------- Glalie
397 -------- GlalieMega Glalie
398 -------- Spheal
399 -------- Sealeo
400 -------- Walrein
401 -------- Clamperl
402 -------- Huntail
403 -------- Gorebyss
404 -------- Relicanth
405 -------- Luvdisc
406 -------- Bagon
407 -------- Shelgon
408 -------- Salamence
409 -------- SalamenceMega Salamence
410 -------- Beldum
411 -------- Metang
412 -------- Metagross
413 -------- MetagrossMega Metagross
414 -------- Regirock
415 -------- Regice
416 -------- Registeel
417 -------- Latias
418 -------- LatiasMega Latias
419 -------- Latios
420 -------- LatiosMega Latios
421 -------- Kyogre
422 -------- KyogrePrimal Kyogre
423 -------- Groudon
424 -------- GroudonPrimal Groudon
425 -------- Rayquaza
426 -------- RayquazaMega Rayquaza
427 -------- Jirachi
428 -------- DeoxysNormal Forme
429 -------- DeoxysAttack Forme
430 -------- DeoxysDefense Forme
431 -------- DeoxysSpeed Forme
432 -------- Turtwig
433 -------- Grotle
434 -------- Torterra
435 -------- Chimchar
436 -------- Monferno
437 -------- Infernape
438 -------- Piplup
439 -------- Prinplup
440 -------- Empoleon
441 -------- Starly
442 -------- Staravia
443 -------- Staraptor
444 -------- Bidoof
445 -------- Bibarel
446 -------- Kricketot
447 -------- Kricketune
448 -------- Shinx
449 -------- Luxio
450 -------- Luxray
451 -------- Budew
452 -------- Roserade
453 -------- Cranidos
454 -------- Rampardos
455 -------- Shieldon
456 -------- Bastiodon
457 -------- Burmy
458 -------- WormadamPlant Cloak
459 -------- WormadamSandy Cloak
460 -------- WormadamTrash Cloak
461 -------- Mothim
462 -------- Combee
463 -------- Vespiquen
464 -------- Pachirisu
465 -------- Buizel
466 -------- Floatzel
467 -------- Cherubi
468 -------- Cherrim
469 -------- Shellos
470 -------- Gastrodon
471 -------- Ambipom
472 -------- Drifloon
473 -------- Drifblim
474 -------- Buneary
475 -------- Lopunny
476 -------- LopunnyMega Lopunny
477 -------- Mismagius
478 -------- Honchkrow
479 -------- Glameow
480 -------- Purugly
481 -------- Chingling
482 -------- Stunky
483 -------- Skuntank
484 -------- Bronzor
485 -------- Bronzong
486 -------- Bonsly
487 -------- Mime Jr.
488 -------- Happiny
489 -------- Chatot
490 -------- Spiritomb
491 -------- Gible
492 -------- Gabite
493 -------- Garchomp
494 -------- GarchompMega Garchomp
495 -------- Munchlax
496 -------- Riolu
497 -------- Lucario
498 -------- LucarioMega Lucario
499 -------- Hippopotas
500 -------- Hippowdon
501 -------- Skorupi
502 -------- Drapion
503 -------- Croagunk
504 -------- Toxicroak
505 -------- Carnivine
506 -------- Finneon
507 -------- Lumineon
508 -------- Mantyke
509 -------- Snover
510 -------- Abomasnow
511 -------- AbomasnowMega Abomasnow
512 -------- Weavile
513 -------- Magnezone
514 -------- Lickilicky
515 -------- Rhyperior
516 -------- Tangrowth
517 -------- Electivire
518 -------- Magmortar
519 -------- Togekiss
520 -------- Yanmega
521 -------- Leafeon
522 -------- Glaceon
523 -------- Gliscor
524 -------- Mamoswine
525 -------- Porygon-Z
526 -------- Gallade
527 -------- GalladeMega Gallade
528 -------- Probopass
529 -------- Dusknoir
530 -------- Froslass
531 -------- Rotom
532 -------- RotomHeat Rotom
533 -------- RotomWash Rotom
534 -------- RotomFrost Rotom
535 -------- RotomFan Rotom
536 -------- RotomMow Rotom
537 -------- Uxie
538 -------- Mesprit
539 -------- Azelf
540 -------- Dialga
541 -------- Palkia
542 -------- Heatran
543 -------- Regigigas
544 -------- GiratinaAltered Forme
545 -------- GiratinaOrigin Forme
546 -------- Cresselia
547 -------- Phione
548 -------- Manaphy
549 -------- Darkrai
550 -------- ShayminLand Forme
551 -------- ShayminSky Forme
552 -------- Arceus
553 -------- Victini
554 -------- Snivy
555 -------- Servine
556 -------- Serperior
557 -------- Tepig
558 -------- Pignite
559 -------- Emboar
560 -------- Oshawott
561 -------- Dewott
562 -------- Samurott
563 -------- Patrat
564 -------- Watchog
565 -------- Lillipup
566 -------- Herdier
567 -------- Stoutland
568 -------- Purrloin
569 -------- Liepard
570 -------- Pansage
571 -------- Simisage
572 -------- Pansear
573 -------- Simisear
574 -------- Panpour
575 -------- Simipour
576 -------- Munna
577 -------- Musharna
578 -------- Pidove

579 -------- Tranquill
580 -------- Unfezant
581 -------- Blitzle
582 -------- Zebstrika
583 -------- Roggenrola
584 -------- Boldore
585 -------- Gigalith
586 -------- Woobat
587 -------- Swoobat
588 -------- Drilbur
589 -------- Excadrill
590 -------- Audino
591 -------- AudinoMega Audino
592 -------- Timburr
593 -------- Gurdurr
594 -------- Conkeldurr
595 -------- Tympole
596 -------- Palpitoad
597 -------- Seismitoad
598 -------- Throh
599 -------- Sawk
600 -------- Sewaddle
601 -------- Swadloon
602 -------- Leavanny
603 -------- Venipede
604 -------- Whirlipede
605 -------- Scolipede
606 -------- Cottonee
607 -------- Whimsicott
608 -------- Petilil
609 -------- Lilligant
610 -------- Basculin
611 -------- Sandile
612 -------- Krokorok
613 -------- Krookodile
614 -------- Darumaka
615 -------- DarmanitanStandard Mode
616 -------- DarmanitanZen Mode
617 -------- Maractus
618 -------- Dwebble
619 -------- Crustle
620 -------- Scraggy
621 -------- Scrafty
622 -------- Sigilyph
623 -------- Yamask
624 -------- Cofagrigus
625 -------- Tirtouga
626 -------- Carracosta
627 -------- Archen
628 -------- Archeops
629 -------- Trubbish
630 -------- Garbodor
631 -------- Zorua
632 -------- Zoroark
633 -------- Minccino
634 -------- Cinccino
635 -------- Gothita
636 -------- Gothorita
637 -------- Gothitelle
638 -------- Solosis
639 -------- Duosion
640 -------- Reuniclus
641 -------- Ducklett
642 -------- Swanna
643 -------- Vanillite
644 -------- Vanillish
645 -------- Vanilluxe
646 -------- Deerling
647 -------- Sawsbuck
648 -------- Emolga
649 -------- Karrablast
650 -------- Escavalier
651 -------- Foongus
652 -------- Amoonguss
653 -------- Frillish
654 -------- Jellicent
655 -------- Alomomola
656 -------- Joltik
657 -------- Galvantula
658 -------- Ferroseed
659 -------- Ferrothorn
660 -------- Klink
661 -------- Klang
662 -------- Klinklang
663 -------- Tynamo
664 -------- Eelektrik
665 -------- Eelektross
666 -------- Elgyem
667 -------- Beheeyem
668 -------- Litwick
669 -------- Lampent
670 -------- Chandelure
671 -------- Axew
672 -------- Fraxure
673 -------- Haxorus
674 -------- Cubchoo
675 -------- Beartic
676 -------- Cryogonal
677 -------- Shelmet
678 -------- Accelgor
679 -------- Stunfisk
680 -------- Mienfoo
681 -------- Mienshao
682 -------- Druddigon
683 -------- Golett
684 -------- Golurk
685 -------- Pawniard
686 -------- Bisharp
687 -------- Bouffalant
688 -------- Rufflet
689 -------- Braviary
690 -------- Vullaby
691 -------- Mandibuzz
692 -------- Heatmor
693 -------- Durant
694 -------- Deino
695 -------- Zweilous
696 -------- Hydreigon
697 -------- Larvesta
698 -------- Volcarona
699 -------- Cobalion
700 -------- Terrakion
701 -------- Virizion
702 -------- TornadusIncarnate Forme
703 -------- TornadusTherian Forme
704 -------- ThundurusIncarnate Forme
705 -------- ThundurusTherian Forme
706 -------- Reshiram
707 -------- Zekrom
708 -------- LandorusIncarnate Forme
709 -------- LandorusTherian Forme
710 -------- Kyurem
711 -------- KyuremBlack Kyurem
712 -------- KyuremWhite Kyurem
713 -------- KeldeoOrdinary Forme
714 -------- KeldeoResolute Forme
715 -------- MeloettaAria Forme
716 -------- MeloettaPirouette Forme
717 -------- Genesect
718 -------- Chespin
719 -------- Quilladin
720 -------- Chesnaught
721 -------- Fennekin
722 -------- Braixen
723 -------- Delphox
724 -------- Froakie
725 -------- Frogadier
726 -------- Greninja
727 -------- Bunnelby
728 -------- Diggersby
729 -------- Fletchling
730 -------- Fletchinder
731 -------- Talonflame
732 -------- Scatterbug
733 -------- Spewpa
734 -------- Vivillon
735 -------- Litleo
736 -------- Pyroar
737 -------- Flabébé
738 -------- Floette
739 -------- Florges
740 -------- Skiddo
741 -------- Gogoat
742 -------- Pancham
743 -------- Pangoro
744 -------- Furfrou
745 -------- Espurr
746 -------- MeowsticMale
747 -------- MeowsticFemale
748 -------- Honedge
749 -------- Doublade
750 -------- AegislashBlade Forme
751 -------- AegislashShield Forme
752 -------- Spritzee
753 -------- Aromatisse
754 -------- Swirlix
755 -------- Slurpuff
756 -------- Inkay
757 -------- Malamar
758 -------- Binacle
759 -------- Barbaracle
760 -------- Skrelp
761 -------- Dragalge
762 -------- Clauncher
763 -------- Clawitzer
764 -------- Helioptile
765 -------- Heliolisk
766 -------- Tyrunt
767 -------- Tyrantrum
768 -------- Amaura
769 -------- Aurorus
770 -------- Sylveon
771 -------- Hawlucha
772 -------- Dedenne
773 -------- Carbink
774 -------- Goomy
775 -------- Sliggoo
776 -------- Goodra
777 -------- Klefki
778 -------- Phantump
779 -------- Trevenant
780 -------- PumpkabooAverage Size
781 -------- PumpkabooSmall Size
782 -------- PumpkabooLarge Size
783 -------- PumpkabooSuper Size
784 -------- GourgeistAverage Size
785 -------- GourgeistSmall Size
786 -------- GourgeistLarge Size
787 -------- GourgeistSuper Size
788 -------- Bergmite
789 -------- Avalugg
790 -------- Noibat
791 -------- Noivern
792 -------- Xerneas
793 -------- Yveltal
794 -------- Zygarde50% Forme
795 -------- Diancie
796 -------- DiancieMega Diancie
797 -------- HoopaHoopa Confined
798 -------- HoopaHoopa Unbound
799 -------- Volcanion

In [17]:
# Conditional reading using the "df.loc[]" function
# Display all the rows where the "Type 1" is equal to ""
data_csv.loc[data_csv["Type 1"] == "Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### df.describe()

> **Generate descriptive statistics.**
<br/>
Descriptive statistics include those that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding **NaN** values.
<br/>
Analyzes both numeric and object series, as well as DataFrame column sets of mixed data types.

In [18]:
data_csv.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

### df.sort_values()

> Sort by the values along either axis.
<br/>
Sort the values in both ascending or descending order based on a specific column of the dataframe.

Both in ascending & descending order
+ Sort values of a particular column.
+ Sort values of multiple columns. Done ordeing in 0 & 1 inside of a list.

In [19]:
data_csv.sort_values('Name') # re-order the rows in ascending order based on the values of "Name" column.

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [20]:
data_csv.sort_values('Name', ascending=False) # re-order the rows in descending order based on the values of "Name" column.

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [21]:
# Sort values of multiple columns.
# Columns should be passed inside of a list.
# Ordering will be defined in 0 & 1 inside of a list which indicates accordingly ascending or descending order

# Take the values of "Type 1" & "HP" columns. Default order will be of ascending values of both the columns.
data_csv.sort_values(["Type 1", "HP"])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
462,415,Combee,Bug,Flying,30,30,42,30,42,70,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
314,290,Nincada,Bug,Ground,31,45,90,30,30,40,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False

In [22]:
# Descending of all columns while sorting values.
data_csv.sort_values(["Type 1", "HP"], ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
314,290,Nincada,Bug,Ground,31,45,90,30,30,40,3,False
462,415,Combee,Bug,Flying,30,30,42,30,42,70,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False

In [23]:
# Sort the values of 2 columns where the "HP" column will be in descending order
# Define a list containing only [True(1), False(0)] inside the "ascending" attribute of the "sort_values()" function.
data_csv.sort_values(["Type 1", "HP"], ascending=[True, False])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

In [24]:
# Sort values based on "Type 1", "HP" where the first & second column will be ordered into False & True accordingly.
data_csv.sort_values(["Type 1", "HP"], ascending=[0, 1])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False
97,90,Shellder,Water,NaN,30,65,100,45,25,40,1,False
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
734,666,Vivillon,Bug,Flying,80,52,50,90,50,89,6,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False

### Make changes in the data

In [25]:
data_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

### Create a "Total" column uisng the conventional way

In [26]:
# Calculate the total of the numeric vlaues of columns: "HP", "Attack", "Defense", "Sp. Attack", "Sp. Defense", "Speed"
# "Sp. Attack" = Special Attack; "Sp. Defense" = Special Defense.
data_csv["Total"] = data_csv["HP"] + data_csv["Attack"] + data_csv["Defense"] + data_csv["Sp. Atk"] + data_csv["Sp. Def"] + data_csv["Speed"]

In [27]:
data_csv.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

### Create a "Total2" column using the "iloc[]" & "sum()" func

> This column will contain the aggregated value of the same **"HP", "Attack", "Defense", "Sp. Attack", "Sp. Defense", "Speed"** columns.

In [28]:
# Need to specify the axis=1, otherwise it'll execute the summation horizontally.
data_csv["Total2"] = data_csv.iloc[:, 4:10].sum(axis=1)

In [29]:
data_csv.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309

### Rearranging column

> Rearrange the "total" column before the "HP" column.

+ **Type-1**: Rearranging into the conventional way.
+ **Type-2**: Rearranging into calling the list-slicing of the columns.

In [30]:
data_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
 12  Total       800 non-null    int64
 13  Total2      800 non-null    int64
dtypes: bool(1), int64(10), object(3)
memory usage: 82.2+ KB

In [31]:
# Type-1: Rearranging by manually calling the columns an concatenating them in the conventional manner.
data_csv_rearranged = data_csv[["#", "Name", "Type 1", "Type 2", "Total2", "HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed", "Generation", "Legendary", "Total"]]
data_csv_rearranged.head()

,#,Name,Type 1,Type 2,Total2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,309

In [32]:
# print(len(data_csv_rearranged.columns.values))
type(data_csv_rearranged.columns)

pandas.core.indexes.base.Index

In [33]:
# Type-2: Rearrange the "Total" column in more abstract manner (using list-slicing)
# It'll require list as the param of the dataframe, because the initial list-elems are envoked by list-slicing. Thus the other elements will also require to be list elems in a list-format, otherwise Python cannot concatenate other list-elements
cols = list(data_csv.columns) # returns a list;
# type(cols[-1])
data_csv_rearranged2 = data_csv[cols[:4] + [cols[-1]] + cols[5:-1]]

### Delete an entire column

Use any of the two methods:
+ **df.drop(colName, axis=1)**
+ **df.drop([colName1, colName2], axis=1)**

In [34]:
# Delete any of the "Total" or "Total2" column
# Use the "df.drop()" function;
# Define the "columnName" with quatation inside the "df.drop()" func;
# Define multiple "columnNames" enclosed with the square-brackets inside the func.
# data_csv.drop("Total2", axis=0) # it'll search in the dataframe-index to find & remove the row
data_csv_dropped_total2 = data_csv.drop("Total2", axis=1) # it'll search for the column in order to drop the entire column.
data_csv_dropped_total2.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

### Save the dataframe into 3 types in the physical storage
+ #### To CSV
+ #### To Excel
+ #### To Text

In [35]:
# This will create a new CSV file into the current directory where this ".ipynb" file is stored
data_csv_rearranged2.to_csv("data_modified.csv", index=False) # Stop the dataframe-index while storing the data into physical storage

In [36]:
# Same; but stores as excel-format
data_csv_rearranged2.to_excel("data_modified.xlsx", index=False)

In [37]:
# Same; but stores as text-format; "\t" seperated-format by using "sep" attr
data_csv_rearranged2.to_csv("data_modified.txt", index=False, sep="\t")

### FIlter data

> Advance Filtering with "**df.loc[]**" function

Syntax of "**df.loc[]**"
`df.loc[row(Label), columnLabel]`

[ **Note** ]: While invoking multiple row & column names, we've to enclose them using square-brackets.

+ Using boolean expression <br/>
    [ Note ]: <br/>
    + for using the Python's "and" inside of the pandas-dataframe, use "**&**";
    + for using the Python's "or" inside of the pandas-dataframe, use "**|**";
+ Using ranges of rows & columns labels
+ Using multiple rows & columns in a list-format
+ Using regex-filtration (filter based on textual pattern)

In [38]:
# Display the totals of each type-1 of pokemons
data_csv["Type 1"].value_counts()

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

In [39]:
# Only view the pokemons of type-1="Grass" values;
# Use boolean expression inside the "df.loc[]" function for filtration;
# Inside the "df.loc[]" function, we're checking the value of "Type 1=Grass" through every rows of the datafrmae;

# Single conditional expression
data_filter1 = data_csv[data_csv["Type 1"] == "Grass"]
data_filter1

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False,320,320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False,313,313
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False,405,405
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False,530,530
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,350,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531,531

In [40]:
# [ Task ]: Display all the pokemons of "Type 1 == Grass" & "HP >= 50"
# Same boolean expression filtration;
# Multiple conditional expressions;
# Need to enclose each conditions inside paranthesis for seperating then;
# Use "**and(&)**" conditionals;
data_filter2 = data_csv[(data_csv["Type 1"] == "Grass") & (data_csv["HP"] >= 50)]
data_filter2

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False,395,395
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,490,490
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False,300,300
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False,390,390
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False,490,490
110,102,Exeggcute,Grass,Psychic,60,40,80,60,45,40,1,False,325,325
111,103,Exeggutor,Grass,Psychic,95,95,85,125,65,55,1,False,520,520
122,114,Tangela,Grass,NaN,65,55,115,100,40,60,1,False,435,435
167,153,Bayleef,Grass,NaN,60,62,80,63,80,60,2,False,405,405
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False,525,525
197,182,Bellossom,Grass,NaN,75,80,95,90,100,50,2,False,490,490
203,188,Skiploom,Grass,Flying,55,45,50,45,65,80,2,False,340,340
204,189,Jumpluff,Grass,Flying,75,55,70,55,95,110,2,False,460,460
207,192,Sunflora,Grass,NaN,75,75,55,105,85,30,2,False,425,425
273,253,Grovyle,Grass,NaN,50,65,45,85,65,95,3,False,405,405
274,254,Sceptile,Grass,NaN,70,85,65,105,85,120,3,False,530,530
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False,630,630
297,274,Nuzleaf,Grass,Dark,70,70,40,60,40,60,3,False,340,340
298,275,Shiftry,Grass,Dark,90,100,60,90,60,80,3,False,480,480
309,285,Shroomish,Grass,NaN,60,40,60,40,60,35,3,False,295,295
310,286,Breloom,Grass,Fighting,60,130,80,60,60,70,3,False,460,460
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False,400,400
362,331,Cacnea,Grass,NaN,50,85,40,85,40,35,3,False,335,335
363,332,Cacturne,Grass,Dark,70,115,60,115,60,55,3,False,475,475
390,357,Tropius,Grass,Flying,99,68,83,72,87,51,3,False,460,460
432,387,Turtwig,Grass,NaN,55,68,64,45,55,31,4,False,318,318
433,388,Grotle,Grass,NaN,75,89,85,55,65,36,4,False,405,405
434,389,Torterra,Grass,Ground,95,109,105,75,85,56,4,False,525,525
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False,515,515
468,421,Cherrim,Grass,NaN,70,60,70,87,78,85,4,False,450,450
505,455,Carnivine,Grass,NaN,74,100,72,90,72,46,4,False,454,454
509,459,Snover,Grass,Ice,60,62,50,62,60,40,4,False,334,334
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False,494,494
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False,594,594
516,465,Tangrowth,Grass,NaN,100,100,125,110,50,50,4,False,535,535
521,470,Leafeon,Grass,NaN,65,110,130,60,65,95,4,False,525,525
550,492,ShayminLand Forme,Grass,NaN,100,100,100,100,100,100,4,True,600,600
551,492,ShayminSky Forme,Grass,Flying,100,103,75,120,75,127,4,True,600,600
555,496,Servine,Grass,NaN,60,60,75,60,75,83,5,False,413,413
556,497,Serperior,Grass,NaN,75,75,95,75,95,113,5,False,528,528
570,511,Pansage,Grass,NaN,50,53,48,53,48,64,5,False,316,316
571,512,Simisage,Grass,NaN,75,98,63,98,63,101,5,False,498,498
607,547,Whimsicott,Grass,Fairy,60,67,85,77,75,116,5,False,480,480
609,549,Lilligant,Grass,NaN,70,60,75,110,75,90,5,False,480,480
617,556,Maractus,Grass,NaN,75,86,67,106,67,60,5,False,461,461
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False,294,294
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False,464,464
659,598,Ferrothorn,Grass,Steel,74,94,131,54,116,20,5,False,489,489
701,640,Virizion,Grass,Fighting,91,90,72,90,129,108,5,True,580,580
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False,313,313
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False,405,405
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False,530,530
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,350,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531,531

In [41]:
# [ Task ]: Display all the pokemons of "Type 1 == Grass" or "Type 2 == Poison"
# Same boolean expression filtration;
# Multiple conditional expressions;
# Need to enclose each conditions inside paranthesis for seperating then;
# Use "**or(|)**" conditionals;
data_filter3 = data_csv[(data_csv["Type 1"] == "Grass") | (data_csv["Type 2"] == "Water")]
data_filter3

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False,320,320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531,531
758,688,Binacle,Rock,Water,42,52,67,39,56,50,6,False,306,306
759,689,Barbaracle,Rock,Water,72,105,115,54,86,68,6,False,500,500
760,690,Skrelp,Poison,Water,50,60,60,60,60,30,6,False,320,320
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

In [42]:
# Task: Display only the pokemons of whether the "Type 1==Grass" or "Type 2==Water" and of "HP>70"
# Bothe use cases of "and(&)", "or(|)" in the same boolean filtration.
data_filter4 = data_csv[(data_csv["Type 1"] == "Grass") | (data_csv["Type 2"] == "Water") & (data_csv["HP"] >= 70)]
data_filter4

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False,320,320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False,530,530
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,350,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531,531
759,689,Barbaracle,Rock,Water,72,105,115,54,86,68,6,False,500,500
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

### Reset index after dataframe-filtration

> When we filter our dataframe, it shirnks in size, thus the index might become scattered. So, we should reset the index in ascending order using the "**df.reset_index()**" function.

In [43]:
data_csv_reset_index = data_filter4.reset_index()
data_csv_reset_index

,index,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False,320,320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False,530,530
73,740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,350,350
74,741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531,531
75,759,689,Barbaracle,Rock,Water,72,105,115,54,86,68,6,False,500,500
76,799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

In [44]:
# Display index values of "data_filter4" in a list
data_filter4_index_list = list(data_filter4.index)

In [45]:
# Display the index of the modified dataframe where the indexes are reset
data_csv_reset_index_list = list(data_csv_reset_index.index)

In [46]:
# Display the differences of both the previous & new index of the filtered dataframe
for old,new in zip(data_filter4_index_list, data_csv_reset_index_list):
    print(old, "------", new)

0 ------ 0
1 ------ 1
2 ------ 2
3 ------ 3
48 ------ 4
49 ------ 5
50 ------ 6
75 ------ 7
76 ------ 8
77 ------ 9
110 ------ 10
111 ------ 11
122 ------ 12
150 ------ 13
166 ------ 14
167 ------ 15
168 ------ 16
197 ------ 17
202 ------ 18
203 ------ 19
204 ------ 20
206 ------ 21
207 ------ 22
272 ------ 23
273 ------ 24
274 ------ 25
275 ------ 26
296 ------ 27
297 ------ 28
298 ------ 29
309 ------ 30
310 ------ 31
344 ------ 32
362 ------ 33
363 ------ 34
390 ------ 35
398 ------ 36
399 ------ 37
400 ------ 38
432 ------ 39
433 ------ 40
434 ------ 41
445 ------ 42
451 ------ 43
452 ------ 44
467 ------ 45
468 ------ 46
505 ------ 47
509 ------ 48
510 ------ 49
511 ------ 50
516 ------ 51
521 ------ 52
550 ------ 53
551 ------ 54
554 ------ 55
555 ------ 56
556 ------ 57
570 ------ 58
571 ------ 59
606 ------ 60
607 ------ 61
608 ------ 62
609 ------ 63
617 ------ 64
651 ------ 65
652 ------ 66
658 ------ 67
659 ------ 68
701 ------ 69
718 ------ 70
719 ------ 71
720 ------ 72
740 ------ 73
741 ------ 74
759 ------ 75
799 ------ 76

### Regex Filtering (Boolean Filtering on textual pattern)

> **pandas.Series.str.contains(self, pat, case=True, flags=0, na=None, regex=True)**

[**[Source] - Series.str.contains()**](https://github.com/pandas-dev/pandas/blob/v1.4.2/pandas/core/strings/accessor.py#L143-L3148)

[**[Doc] - pandas.Series.str()**](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.html)

+ Same "**df.loc[]**" function is called; boolean filtering is used while using the _regex-filtering_ on a particular column.

In [59]:
# Display all the pokemons whose name contain "Mega".
data_csv.loc[data_csv["Name"].str.contains(pat="Mega")]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634,634
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False,630,630
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False,495,495
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579,579
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False,590,590
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False,590,590
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False,600,600
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,1,False,590,590
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600,600
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False,640,640
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False,615,615
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True,780,780
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True,780,780
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False,525,525
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,2,False,610,610
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,2,False,610,610
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False,600,600
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False,600,600
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,2,False,600,600
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False,700,700
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False,630,630
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,630,630
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,3,False,635,635
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3,False,618,618
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,3,False,480,480
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,3,False,480,480
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False,630,630
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,3,False,510,510
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,3,False,575,575
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,3,False,560,560
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False,560,560
366,334,AltariaMega Altaria,Dragon,Fairy,75,110,110,110,105,80,3,False,590,590
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False,555,555
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False,565,565
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,3,False,580,580
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,3,False,700,700
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,3,False,700,700
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,3,True,700,700
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,3,True,700,700
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True,780,780
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,4,False,580,580
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,4,False,700,700
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,4,False,625,625
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False,594,594
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False,618,618
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,5,False,545,545
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,700

In [60]:
# Display all the pokemons whose name do not contain "Mega".
data_csv.loc[~data_csv["Name"].str.contains(pat="Mega")]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True,600,600
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,600
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

In [64]:
# Display all the pokemons whose "Type 1" of "Grass/Fire".
data_csv.loc[data_csv["Type 1"].str.contains(pat="Grass|Fire")] # the regex-attr is True by default

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False,369,369
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,507,507
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,350,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531,531
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

In [68]:
# Display the pokemons of "Type 1" of both "Grass" or "Fire";
# For matching the string-literal regardless of the letter-casing, we need to define the "flags" attr to refer to the "re module".
import re
data_csv.loc[data_csv["Type 1"].str.contains(pat="grass|fire", flags=re.I)] # matches the string-literal pattern regardless of being case-sensitive

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False,369,369
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,507,507
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,350,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531,531
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

In [72]:
# Display the pokemon names started with "pi".
# Symbol "^" => Caret/ Circumflex Accent

data_csv.loc[data_csv["Name"].str.contains(pat="^pi", flags=re.I)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251,251
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349,349
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479,479
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579,579
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False,320,320
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False,500,500
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600,600
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,205,205
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False,290,290
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450,450
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False,314,314
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418,418
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,264,264

### Conditional Changes

In [77]:
# Display all the pokemon of "Type 1" == "Fire"
data_csv.loc[data_csv["Type 1"] == "Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405,405
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,534,534
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634,634
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False,299,299
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False,505,505
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False,350,350
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False,555,555
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False,410,410
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False,500,500
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False,495,495
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False,525,525
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True,580,580
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False,309,309
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False,405,405
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False,534,534
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False,250,250
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False,410,410
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False,365,365
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True,580,580
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680,680
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False,310,310
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False,405,405
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False,530,530
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,630,630
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False,305,305
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False,460,460
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False,560,560
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False,470,470
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False,309,309
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False,405,405
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False,534,534
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False,540,540
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True,600,600
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False,308,308
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418,418
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False,528,528
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False,316,316
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False,498,498
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False,315,315
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False,480,480
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False,540,540
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False,484,484
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False,307,307
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False,409,409
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False,534,534
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False,382,382
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False,499,499
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False,369,369
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,507,507
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600,600

In [82]:
# Change the values od column "Type 1" of "Fire" pokemons to "Flammer"
data_csv.loc[data_csv["Type 1"] == "Fire", "Type 1"] = "Flammer"
data_csv

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625,625
4,4,Charmander,Flammer,NaN,39,52,43,60,50,65,1,False,309,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680,680
799,721,Volcanion,Flammer,Water,80,110,120,130,90,70,6,True,600,600

In [91]:
# Display the pokemons of "Type 1=Flammer" and "Legendary=True"
data_csv.loc[(data_csv["Type 1"] == "Flammer") & (data_csv["Legendary"])]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
158,146,Moltres,Flammer,Flying,90,100,90,125,85,90,1,True,580,580
263,244,Entei,Flammer,NaN,115,115,85,90,75,100,2,True,580,580
270,250,Ho-oh,Flammer,Flying,106,130,90,110,154,90,2,True,680,680
542,485,Heatran,Flammer,Steel,91,90,106,130,106,77,4,True,600,600
799,721,Volcanion,Flammer,Water,80,110,120,130,90,70,6,True,600,600

In [92]:
# Display the pokemons of "Type 1=Flammer" and "Legendary=False" using the "squiggly" symbol
data_csv.loc[(data_csv["Type 1"] == "Flammer") & (~data_csv["Legendary"])]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
4,4,Charmander,Flammer,NaN,39,52,43,60,50,65,1,False,309,309
5,5,Charmeleon,Flammer,NaN,58,64,58,80,65,80,1,False,405,405
6,6,Charizard,Flammer,Flying,78,84,78,109,85,100,1,False,534,534
7,6,CharizardMega Charizard X,Flammer,Dragon,78,130,111,130,85,100,1,False,634,634
8,6,CharizardMega Charizard Y,Flammer,Flying,78,104,78,159,115,100,1,False,634,634
42,37,Vulpix,Flammer,NaN,38,41,40,50,65,65,1,False,299,299
43,38,Ninetales,Flammer,NaN,73,76,75,81,100,100,1,False,505,505
63,58,Growlithe,Flammer,NaN,55,70,45,70,50,60,1,False,350,350
64,59,Arcanine,Flammer,NaN,90,110,80,100,80,95,1,False,555,555
83,77,Ponyta,Flammer,NaN,50,85,55,65,65,90,1,False,410,410
84,78,Rapidash,Flammer,NaN,65,100,70,80,80,105,1,False,500,500
135,126,Magmar,Flammer,NaN,65,95,57,100,85,93,1,False,495,495
147,136,Flareon,Flammer,NaN,65,130,60,95,110,65,1,False,525,525
169,155,Cyndaquil,Flammer,NaN,39,52,43,60,50,65,2,False,309,309
170,156,Quilava,Flammer,NaN,58,64,58,80,65,80,2,False,405,405
171,157,Typhlosion,Flammer,NaN,78,84,78,109,85,100,2,False,534,534
236,218,Slugma,Flammer,NaN,40,40,40,70,40,20,2,False,250,250
237,219,Magcargo,Flammer,Rock,50,50,120,80,80,30,2,False,410,410
259,240,Magby,Flammer,NaN,45,75,37,70,55,83,2,False,365,365
276,255,Torchic,Flammer,NaN,45,60,40,70,50,45,3,False,310,310
277,256,Combusken,Flammer,Fighting,60,85,60,85,60,55,3,False,405,405
278,257,Blaziken,Flammer,Fighting,80,120,70,110,70,80,3,False,530,530
279,257,BlazikenMega Blaziken,Flammer,Fighting,80,160,80,130,80,100,3,False,630,630
352,322,Numel,Flammer,Ground,60,60,40,65,45,35,3,False,305,305
353,323,Camerupt,Flammer,Ground,70,100,70,105,75,40,3,False,460,460
354,323,CameruptMega Camerupt,Flammer,Ground,70,120,100,145,105,20,3,False,560,560
355,324,Torkoal,Flammer,NaN,70,85,140,85,70,20,3,False,470,470
435,390,Chimchar,Flammer,NaN,44,58,44,58,44,61,4,False,309,309
436,391,Monferno,Flammer,Fighting,64,78,52,78,52,81,4,False,405,405
437,392,Infernape,Flammer,Fighting,76,104,71,104,71,108,4,False,534,534
518,467,Magmortar,Flammer,NaN,75,95,67,125,95,83,4,False,540,540
557,498,Tepig,Flammer,NaN,65,63,45,45,45,45,5,False,308,308
558,499,Pignite,Flammer,Fighting,90,93,55,70,55,55,5,False,418,418
559,500,Emboar,Flammer,Fighting,110,123,65,100,65,65,5,False,528,528
572,513,Pansear,Flammer,NaN,50,53,48,53,48,64,5,False,316,316
573,514,Simisear,Flammer,NaN,75,98,63,98,63,101,5,False,498,498
614,554,Darumaka,Flammer,NaN,70,90,45,15,45,50,5,False,315,315
615,555,DarmanitanStandard Mode,Flammer,NaN,105,140,55,30,55,95,5,False,480,480
616,555,DarmanitanZen Mode,Flammer,Psychic,105,30,105,140,105,55,5,False,540,540
692,631,Heatmor,Flammer,NaN,85,97,66,105,66,65,5,False,484,484
721,653,Fennekin,Flammer,NaN,40,45,40,62,60,60,6,False,307,307
722,654,Braixen,Flammer,NaN,59,59,58,90,70,73,6,False,409,409
723,655,Delphox,Flammer,Psychic,75,69,72,114,100,104,6,False,534,534
730,662,Fletchinder,Flammer,Flying,62,73,55,56,52,84,6,False,382,382
731,663,Talonflame,Flammer,Flying,78,81,71,74,69,126,6,False,499,499
735,667,Litleo,Flammer,Normal,62,50,58,73,54,72,6,False,369,369
736,668,Pyroar,Flammer,Normal,86,68,72,109,66,106,6,False,507,507

In [93]:
# Change the pokemons of "Type 1=Flammer" and "Legendary=False" to True
data_csv.loc[(data_csv["Type 1"] == "Flammer") & (~data_csv["Legendary"]), "Legendary"] = True

In [95]:
# Display the pokemons of "Type 1=Flammer" to check if their "Legendary=True"
data_csv.loc[data_csv["Type 1"] == "Flammer"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
4,4,Charmander,Flammer,NaN,39,52,43,60,50,65,1,True,309,309
5,5,Charmeleon,Flammer,NaN,58,64,58,80,65,80,1,True,405,405
6,6,Charizard,Flammer,Flying,78,84,78,109,85,100,1,True,534,534
7,6,CharizardMega Charizard X,Flammer,Dragon,78,130,111,130,85,100,1,True,634,634
8,6,CharizardMega Charizard Y,Flammer,Flying,78,104,78,159,115,100,1,True,634,634
42,37,Vulpix,Flammer,NaN,38,41,40,50,65,65,1,True,299,299
43,38,Ninetales,Flammer,NaN,73,76,75,81,100,100,1,True,505,505
63,58,Growlithe,Flammer,NaN,55,70,45,70,50,60,1,True,350,350
64,59,Arcanine,Flammer,NaN,90,110,80,100,80,95,1,True,555,555
83,77,Ponyta,Flammer,NaN,50,85,55,65,65,90,1,True,410,410
84,78,Rapidash,Flammer,NaN,65,100,70,80,80,105,1,True,500,500
135,126,Magmar,Flammer,NaN,65,95,57,100,85,93,1,True,495,495
147,136,Flareon,Flammer,NaN,65,130,60,95,110,65,1,True,525,525
158,146,Moltres,Flammer,Flying,90,100,90,125,85,90,1,True,580,580
169,155,Cyndaquil,Flammer,NaN,39,52,43,60,50,65,2,True,309,309
170,156,Quilava,Flammer,NaN,58,64,58,80,65,80,2,True,405,405
171,157,Typhlosion,Flammer,NaN,78,84,78,109,85,100,2,True,534,534
236,218,Slugma,Flammer,NaN,40,40,40,70,40,20,2,True,250,250
237,219,Magcargo,Flammer,Rock,50,50,120,80,80,30,2,True,410,410
259,240,Magby,Flammer,NaN,45,75,37,70,55,83,2,True,365,365
263,244,Entei,Flammer,NaN,115,115,85,90,75,100,2,True,580,580
270,250,Ho-oh,Flammer,Flying,106,130,90,110,154,90,2,True,680,680
276,255,Torchic,Flammer,NaN,45,60,40,70,50,45,3,True,310,310
277,256,Combusken,Flammer,Fighting,60,85,60,85,60,55,3,True,405,405
278,257,Blaziken,Flammer,Fighting,80,120,70,110,70,80,3,True,530,530
279,257,BlazikenMega Blaziken,Flammer,Fighting,80,160,80,130,80,100,3,True,630,630
352,322,Numel,Flammer,Ground,60,60,40,65,45,35,3,True,305,305
353,323,Camerupt,Flammer,Ground,70,100,70,105,75,40,3,True,460,460
354,323,CameruptMega Camerupt,Flammer,Ground,70,120,100,145,105,20,3,True,560,560
355,324,Torkoal,Flammer,NaN,70,85,140,85,70,20,3,True,470,470
435,390,Chimchar,Flammer,NaN,44,58,44,58,44,61,4,True,309,309
436,391,Monferno,Flammer,Fighting,64,78,52,78,52,81,4,True,405,405
437,392,Infernape,Flammer,Fighting,76,104,71,104,71,108,4,True,534,534
518,467,Magmortar,Flammer,NaN,75,95,67,125,95,83,4,True,540,540
542,485,Heatran,Flammer,Steel,91,90,106,130,106,77,4,True,600,600
557,498,Tepig,Flammer,NaN,65,63,45,45,45,45,5,True,308,308
558,499,Pignite,Flammer,Fighting,90,93,55,70,55,55,5,True,418,418
559,500,Emboar,Flammer,Fighting,110,123,65,100,65,65,5,True,528,528
572,513,Pansear,Flammer,NaN,50,53,48,53,48,64,5,True,316,316
573,514,Simisear,Flammer,NaN,75,98,63,98,63,101,5,True,498,498
614,554,Darumaka,Flammer,NaN,70,90,45,15,45,50,5,True,315,315
615,555,DarmanitanStandard Mode,Flammer,NaN,105,140,55,30,55,95,5,True,480,480
616,555,DarmanitanZen Mode,Flammer,Psychic,105,30,105,140,105,55,5,True,540,540
692,631,Heatmor,Flammer,NaN,85,97,66,105,66,65,5,True,484,484
721,653,Fennekin,Flammer,NaN,40,45,40,62,60,60,6,True,307,307
722,654,Braixen,Flammer,NaN,59,59,58,90,70,73,6,True,409,409
723,655,Delphox,Flammer,Psychic,75,69,72,114,100,104,6,True,534,534
730,662,Fletchinder,Flammer,Flying,62,73,55,56,52,84,6,True,382,382
731,663,Talonflame,Flammer,Flying,78,81,71,74,69,126,6,True,499,499
735,667,Litleo,Flammer,Normal,62,50,58,73,54,72,6,True,369,369
736,668,Pyroar,Flammer,Normal,86,68,72,109,66,106,6,True,507,507
799,721,Volcanion,Flammer,Water,80,110,120,130,90,70,6,True,600,600

In [96]:
# Change multiple columns' values by using boolean filtering
# Change the values of "Generation" & "Legendary" to "TEST VALUE" where the pokemons' "Total" is greater tham 500
data_csv.loc[data_csv["Total"] > 500, ["Generation", "Legendary"]] = "TEST VALUE"
data_csv

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,TEST VALUE,TEST VALUE,525,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,TEST VALUE,TEST VALUE,625,625
4,4,Charmander,Flammer,NaN,39,52,43,60,50,65,1,True,309,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,TEST VALUE,TEST VALUE,600,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,TEST VALUE,TEST VALUE,700,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,TEST VALUE,TEST VALUE,600,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,TEST VALUE,TEST VALUE,680,680
799,721,Volcanion,Flammer,Water,80,110,120,130,90,70,TEST VALUE,TEST VALUE,600,600

### df.groupby()

[**Docs**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)

>Group DataFrame using a mapper or by a Series of columns. <br/>
A groupby operation involves some combination of splitting the object, applying a function, and combining the results. This can be used to group large amounts of data and compute operations on these groups.

Pandas groupby is used for grouping the data according to the categories and apply a function to the categories. It also helps to aggregate data efficiently.

Pandas `dataframe.groupby()` function is used to split the data into groups based on some criteria.

**Returns "dataframe"**

In [103]:
# Cluster the dataframe based on the categorical values of "Generation" column.
# data_csv.groupby("Generation") # Provide a "dataframe.groupby" object
for name, group in data_csv.groupby("Generation"):
    print("#"*50)
    print(name)
    print("#"*50)
    print(group)

##################################################
1
##################################################
       #        Name   Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0      1   Bulbasaur    Grass  Poison  45      49       49       65       65
1      2     Ivysaur    Grass  Poison  60      62       63       80       80
4      4  Charmander  Flammer     NaN  39      52       43       60       50
5      5  Charmeleon  Flammer     NaN  58      64       58       80       65
9      7    Squirtle    Water     NaN  44      48       65       50       64
..   ...         ...      ...     ...  ..     ...      ...      ...      ...
150  139     Omastar     Rock   Water  70      60      125      115       70
151  140      Kabuto     Rock   Water  30      80       90       55       45
152  141    Kabutops     Rock   Water  60     115      105       65       70
159  147     Dratini   Dragon     NaN  41      64       45       50       50
160  148   Dragonair   Dragon     NaN  61      84       65       70       70

     Speed Generation Legendary  Total  Total2
0       45          1     False    318     318
1       60          1     False    405     405
4       65          1      True    309     309
5       80          1      True    405     405
9       43          1     False    314     314
..     ...        ...       ...    ...     ...
150     55          1     False    495     495
151     55          1     False    355     355
152     80          1     False    495     495
159     50          1     False    300     300
160     70          1     False    420     420

[126 rows x 14 columns]
##################################################
2
##################################################
       #       Name    Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
166  152  Chikorita     Grass     NaN  45      49       65       49       65
167  153    Bayleef     Grass     NaN  60      62       80       63       80
169  155  Cyndaquil   Flammer     NaN  39      52       43       60       50
170  156    Quilava   Flammer     NaN  58      64       58       80       65
172  158   Totodile     Water     NaN  50      65       64       44       48
..   ...        ...       ...     ...  ..     ...      ...      ...      ...
258  239     Elekid  Electric     NaN  45      63       37       65       55
259  240      Magby   Flammer     NaN  45      75       37       70       55
260  241    Miltank    Normal     NaN  95      80      105       40       70
265  246   Larvitar      Rock  Ground  50      64       50       45       50
266  247    Pupitar      Rock  Ground  70      84       70       65       70

     Speed Generation Legendary  Total  Total2
166     45          2     False    318     318
167     60          2     False    405     405
169     65          2      True    309     309
170     80          2      True    405     405
172     43          2     False    314     314
..     ...        ...       ...    ...     ...
258     95          2     False    360     360
259     83          2      True    365     365
260    100          2     False    490     490
265     41          2     False    300     300
266     51          2     False    410     410

[81 rows x 14 columns]
##################################################
3
##################################################
       #       Name   Type 1    Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
272  252    Treecko    Grass       NaN  40      45       35       65       55
273  253    Grovyle    Grass       NaN  50      65       45       85       65
276  255    Torchic  Flammer       NaN  45      60       40       70       50
277  256  Combusken  Flammer  Fighting  60      85       60       85       60
280  258     Mudkip    Water       NaN  50      70       50       50       50
..   ...        ...      ...       ...  ..     ...      ...      ...      ...
405  370    Luvdisc    Water       NaN  43      30       55       40       65
406  371      Bagon   Dragon       NaN  45      75       60       40       30
407  372    Shelgon   Dragon       NaN  65      95      100       60       50
410  374     Beldum    Steel   Psychic  40      55       80       35       60
411  375     Metang    Steel   Psychic  60      75      100       55       80

     Speed Generation Legendary  Total  Total2
272     70          3     False    310     310
273     95          3     False    405     405
276     45          3      True    310     310
277     55          3      True    405     405
280     40          3     False    310     310
..     ...        ...       ...    ...     ...
405     97          3     False    330     330
406     50          3     False    300     300
407     50          3     False    420     420
410     30          3     False    300     300
411     50          3     False    420     420

[116 rows x 14 columns]
##################################################
4
##################################################
       #       Name    Type 1    Type 2  HP  Attack  Defense  Sp. Atk  \
432  387    Turtwig     Grass       NaN  55      68       64       45
433  388     Grotle     Grass       NaN  75      89       85       55
435  390   Chimchar   Flammer       NaN  44      58       44       58
436  391   Monferno   Flammer  Fighting  64      78       52       78
438  393     Piplup     Water       NaN  53      51       53       61
..   ...        ...       ...       ...  ..     ...      ...      ...
509  459     Snover     Grass       Ice  60      62       50       62
510  460  Abomasnow     Grass       Ice  90      92       75       92
530  478   Froslass       Ice     Ghost  70      80       70       80
531  479      Rotom  Electric     Ghost  50      50       77       95
547  489     Phione     Water       NaN  80      80       80       80

     Sp. Def  Speed Generation Legendary  Total  Total2
432       55     31          4     False    318     318
433       65     36          4     False    405     405
435       44     61          4      True    309     309
436       52     81          4      True    405     405
438       56     40          4     False    314     314
..       ...    ...        ...       ...    ...     ...
509       60     40          4     False    334     334
510       85     60          4     False    494     494
530       70    110          4     False    480     480
531       77     91          4     False    440     440
547       80     80          4     False    480     480

[70 rows x 14 columns]
##################################################
5
##################################################
       #      Name   Type 1    Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
554  495     Snivy    Grass       NaN  45      45       55       45       55
555  496   Servine    Grass       NaN  60      60       75       60       75
557  498     Tepig  Flammer       NaN  65      63       45       45       45
558  499   Pignite  Flammer  Fighting  90      93       55       70       55
560  501  Oshawott    Water       NaN  55      55       45       63       45
..   ...       ...      ...       ...  ..     ...      ...      ...      ...
692  631   Heatmor  Flammer       NaN  85      97       66      105       66
693  632    Durant      Bug     Steel  58     109      112       48       48
694  633     Deino     Dark    Dragon  52      65       50       45       50
695  634  Zweilous     Dark    Dragon  72      85       70       65       70
697  636  Larvesta      Bug      Fire  55      85       55       50       55

     Speed Generation Legendary  Total  Total2
554     63          5     False    308     308
555     83          5     False    413     413
557     45          5      True    308     308
558     55          5      True    418     418
560     45          5     False    308     308
..     ...        ...       ...    ...     ...
692     65          5      True    484     484
693    109          5     False    484     484
694     38          5     False    300     300
695     58          5     False    420     420
697     60          5     False    360     360

[123 rows x 14 columns]
##################################################
6
##################################################
       #                   Name    Type 1   Type 2   HP  Attack  Defense  \
718  650                Chespin     Grass      NaN   56      61       65
719  651              Quilladin     Grass      NaN   61      78       95
721  653               Fennekin   Flammer      NaN   40      45       40
722  654                Braixen   Flammer      NaN   59      59       58
724  656                Froakie     Water      NaN   41      56       40
725  657              Frogadier     Water      NaN   54      63       52
727  659               Bunnelby    Normal      NaN   38      36       38
728  660              Diggersby    Normal   Ground   85      56       77
729  661             Fletchling    Normal   Flying   45      50       43
730  662            Fletchinder   Flammer   Flying   62      73       55
731  663             Talonflame   Flammer   Flying   78      81       71
732  664             Scatterbug       Bug      NaN   38      35       40
733  665                 Spewpa       Bug      NaN   45      22       60
734  666               Vivillon       Bug   Flying   80      52       50
735  667                 Litleo   Flammer   Normal   62      50       58
737  669                Flabébé     Fairy      NaN   44      38       39
738  670                Floette     Fairy      NaN   54      45       47
740  672                 Skiddo     Grass      NaN   66      65       48
742  674                Pancham  Fighting      NaN   67      82       62
743  675                Pangoro  Fighting     Dark   95     124       78
744  676                Furfrou    Normal      NaN   75      80       60
745  677                 Espurr   Psychic      NaN   62      48       54
746  678           MeowsticMale   Psychic      NaN   74      48       76
747  678         MeowsticFemale   Psychic      NaN   74      48       76
748  679                Honedge     Steel    Ghost   45      80      100
749  680               Doublade     Steel    Ghost   59     110      150
752  682               Spritzee     Fairy      NaN   78      52       60
753  683             Aromatisse     Fairy      NaN  101      72       72
754  684                Swirlix     Fairy      NaN   62      48       66
755  685               Slurpuff     Fairy      NaN   82      80       86
756  686                  Inkay      Dark  Psychic   53      54       53
757  687                Malamar      Dark  Psychic   86      92       88
758  688                Binacle      Rock    Water   42      52       67
759  689             Barbaracle      Rock    Water   72     105      115
760  690                 Skrelp    Poison    Water   50      60       60
761  691               Dragalge    Poison   Dragon   65      75       90
762  692              Clauncher     Water      NaN   50      53       62
763  693              Clawitzer     Water      NaN   71      73       88
764  694             Helioptile  Electric   Normal   44      38       33
765  695              Heliolisk  Electric   Normal   62      55       52
766  696                 Tyrunt      Rock   Dragon   58      89       77
768  698                 Amaura      Rock      Ice   77      59       50
771  701               Hawlucha  Fighting   Flying   78      92       75
772  702                Dedenne  Electric    Fairy   67      58       57
773  703                Carbink      Rock    Fairy   50      50      150
774  704                  Goomy    Dragon      NaN   45      50       35
775  705                Sliggoo    Dragon      NaN   68      75       53
777  707                 Klefki     Steel    Fairy   57      80       91
778  708               Phantump     Ghost    Grass   43      70       48
779  709              Trevenant     Ghost    Grass   85     110       76
780  710  PumpkabooAverage Size     Ghost    Grass   49      66       70
781  710    PumpkabooSmall Size     Ghost    Grass   44      66       70
782  710    PumpkabooLarge Size     Ghost    Grass   54      66       70
783  710    PumpkabooSuper Size     Ghost    Grass   59      66       70
784  711  GourgeistAverage Size     Ghost    Grass   65      90      122
785  711    GourgeistSmall Size     Ghost    Grass   55      85      122
786  711    GourgeistLarge Size     Ghost    Grass   75      95      122
787  711    GourgeistSuper Size     Ghost    Grass   85     100      122
788  712               Bergmite       Ice      NaN   55      69       85
790  714                 Noibat    Flying   Dragon   40      30       35

     Sp. Atk  Sp. Def  Speed Generation Legendary  Total  Total2
718       48       45     38          6     False    313     313
719       56       58     57          6     False    405     405
721       62       60     60          6      True    307     307
722       90       70     73          6      True    409     409
724       62       44     71          6     False    314     314
725       83       56     97          6     False    405     405
727       32       36     57          6     False    237     237
728       50       77     78          6     False    423     423
729       40       38     62          6     False    278     278
730       56       52     84          6      True    382     382
731       74       69    126          6      True    499     499
732       27       25     35          6     False    200     200
733       27       30     29          6     False    213     213
734       90       50     89          6     False    411     411
735       73       54     72          6      True    369     369
737       61       79     42          6     False    303     303
738       75       98     52          6     False    371     371
740       62       57     52          6     False    350     350
742       46       48     43          6     False    348     348
743       69       71     58          6     False    495     495
744       65       90    102          6     False    472     472
745       63       60     68          6     False    355     355
746       83       81    104          6     False    466     466
747       83       81    104          6     False    466     466
748       35       37     28          6     False    325     325
749       45       49     35          6     False    448     448
752       63       65     23          6     False    341     341
753       99       89     29          6     False    462     462
754       59       57     49          6     False    341     341
755       85       75     72          6     False    480     480
756       37       46     45          6     False    288     288
757       68       75     73          6     False    482     482
758       39       56     50          6     False    306     306
759       54       86     68          6     False    500     500
760       60       60     30          6     False    320     320
761       97      123     44          6     False    494     494
762       58       63     44          6     False    330     330
763      120       89     59          6     False    500     500
764       61       43     70          6     False    289     289
765      109       94    109          6     False    481     481
766       45       45     48          6     False    362     362
768       67       63     46          6     False    362     362
771       74       63    118          6     False    500     500
772       81       67    101          6     False    431     431
773       50      150     50          6     False    500     500
774       55       75     40          6     False    300     300
775       83      113     60          6     False    452     452
777       80       87     75          6     False    470     470
778       50       60     38          6     False    309     309
779       65       82     56          6     False    474     474
780       44       55     51          6     False    335     335
781       44       55     56          6     False    335     335
782       44       55     46          6     False    335     335
783       44       55     41          6     False    335     335
784       58       75     84          6     False    494     494
785       58       75     99          6     False    494     494
786       58       75     69          6     False    494     494
787       58       75     54          6     False    494     494
788       32       35     28          6     False    304     304
790       45       40     55          6     False    245     245
##################################################
TEST VALUE
##################################################
       #                       Name   Type 1  Type 2  HP  Attack  Defense  \
2      3                   Venusaur    Grass  Poison  80      82       83
3      3      VenusaurMega Venusaur    Grass  Poison  80     100      123
6      6                  Charizard  Flammer  Flying  78      84       78
7      6  CharizardMega Charizard X  Flammer  Dragon  78     130      111
8      6  CharizardMega Charizard Y  Flammer  Flying  78     104       78
..   ...                        ...      ...     ...  ..     ...      ...
795  719                    Diancie     Rock   Fairy  50     100      150
796  719        DiancieMega Diancie     Rock   Fairy  50     160      110
797  720        HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720         HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721                  Volcanion  Flammer   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation   Legendary  Total  Total2
2        100      100     80  TEST VALUE  TEST VALUE    525     525
3        122      120     80  TEST VALUE  TEST VALUE    625     625
6        109       85    100  TEST VALUE  TEST VALUE    534     534
7        130       85    100  TEST VALUE  TEST VALUE    634     634
8        159      115    100  TEST VALUE  TEST VALUE    634     634
..       ...      ...    ...         ...         ...    ...     ...
795      100      150     50  TEST VALUE  TEST VALUE    600     600
796      160      110    110  TEST VALUE  TEST VALUE    700     700
797      150      130     70  TEST VALUE  TEST VALUE    600     600
798      170      130     80  TEST VALUE  TEST VALUE    680     680
799      130       90     70  TEST VALUE  TEST VALUE    600     600

[224 rows x 14 columns]

In [98]:
dir(data_csv.groupby("Generation"))

['Attack',
 'Defense',
 'Generation',
 'HP',
 'Legendary',
 'Name',
 'Speed',
 'Total',
 'Total2',
 '__annotations__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_accessors',
 '_agg_examples_doc',
 '_agg_general',
 '_agg_py_fallback',
 '_aggregate_frame',
 '_aggregate_item_by_item',
 '_aggregate_with_numba',
 '_apply_allowlist',
 '_apply_filter',
 '_apply_to_column_groupbys',
 '_bool_agg',
 '_can_use_transform_fast',
 '_choose_path',
 '_concat_objects',
 '_constructor',
 '_cumcount_array',
 '_cython_agg_general',
 '_cython_transform',
 '_define_paths',
 '_dir_additions',
 '_dir_deletions',
 '_fill',
 '_get_cythonized_result',
 '_get_data_to_aggregate',
 '_get_index',
 '_get_indices',
 '_gotitem',
 '_group_selection',
 '_hidden_attrs',
 '_insert_inaxis_grouper_inplace',
 '_internal_names',
 '_internal_names_set',
 '_is_protocol',
 '_iterate_column_groupbys',
 '_iterate_slices',
 '_make_wrapper',
 '_numba_prep',
 '_obj_1d_constructor',
 '_obj_with_exclusions',
 '_python_agg_general',
 '_python_apply_general',
 '_reindex_output',
 '_reset_cache',
 '_reset_group_selection',
 '_resolve_numeric_only',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_set_group_selection',
 '_set_result_index_ordered',
 '_transform',
 '_transform_general',
 '_transform_item_by_item',
 '_transform_with_numba',
 '_wrap_agged_manager',
 '_wrap_aggregated_output',
 '_wrap_applied_output',
 '_wrap_applied_output_series',
 '_wrap_transform_fast_result',
 '_wrap_transformed_output',
 'agg',
 'aggregate',
 'all',
 'any',
 'apply',
 'backfill',
 'bfill',
 'boxplot',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cumcount',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'dtypes',
 'ewm',
 'expanding',
 'ffill',
 'fillna',
 'filter',
 'first',
 'get_group',
 'groups',
 'head',
 'hist',
 'idxmax',
 'idxmin',
 'indices',
 'last',
 'mad',
 'max',
 'mean',
 'median',
 'min',
 'ndim',
 'ngroup',
 'ngroups',
 'nth',
 'nunique',
 'ohlc',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'prod',
 'quantile',
 'rank',
 'resample',
 'rolling',
 'sample',
 'sem',
 'shift',
 'size',
 'skew',
 'std',
 'sum',
 'tail',
 'take',
 'transform',
 'tshift',
 'var']

### Aggregated Statistics (Sum, Mean, Count)
**Use some math operations after the "groupby" function**
+ #### mean()
+ #### sum()
+ #### counting()


#### Execute operations (sum, mean & count) after grouping the dataframe based on the "Type 1" column.

In [105]:
# Cluster/group the the pokemons based on the values of "Type 1" column.
data_csv.groupby("Type 1").mean()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Total2
Type 1,,,,,,,,,
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,378.927536,378.927536
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,445.741935,445.741935
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,550.531250,550.531250
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,443.409091,443.409091
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,413.176471,413.176471
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,416.444444,416.444444
Flammer,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,458.076923,458.076923
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,485.000000,485.000000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,439.562500,439.562500
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,421.142857,421.142857
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,437.500000,437.500000
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,433.458333,433.458333
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,401.683673,401.683673
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,399.142857,399.142857
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,475.947368,475.947368
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,453.750000,453.750000
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,487.703704,487.703704
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,430.455357,430.455357

In [117]:
# DIsplay the aggregated count of each pokemon of "Type 1" column
data_csv["Type 1"].value_counts()

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Flammer      52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

In [125]:
# View the highest defense of pokemons using groupby on the "Type 1" column
# Clustered the pokemons based on the "Type 1" column
data_csv.groupby("Type 1").mean().sort_values("Defense", ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Total2
Type 1,,,,,,,,,
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,487.703704,487.703704
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,453.750000,453.750000
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,550.531250,550.531250
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,437.500000,437.500000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,439.562500,439.562500
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,430.455357,430.455357
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,433.458333,433.458333
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,421.142857,421.142857
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,378.927536,378.927536
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,445.741935,445.741935
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,399.142857,399.142857
Flammer,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,458.076923,458.076923
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,475.947368,475.947368
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,443.409091,443.409091
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,485.000000,485.000000
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,416.444444,416.444444
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,413.176471,413.176471
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,401.683673,401.683673

In [126]:
# Culster the pokemons based on the "Type 1" column;
# Then sore the pokemons of the hightest attack value using the "sort_values" function;
data_csv.groupby("Type 1").mean().sort_values("Attack", ascending=False)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Total2
Type 1,,,,,,,,,
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,550.531250,550.531250
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,416.444444,416.444444
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,437.500000,437.500000
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,453.750000,453.750000
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,487.703704,487.703704
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,445.741935,445.741935
Flammer,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,458.076923,458.076923
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,485.000000,485.000000
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,399.142857,399.142857
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,430.455357,430.455357
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,439.562500,439.562500
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,401.683673,401.683673
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,421.142857,421.142857
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,433.458333,433.458333
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,475.947368,475.947368
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,378.927536,378.927536
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,443.409091,443.409091
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,413.176471,413.176471

In [127]:
# Cluster/groupedby the pokemons based on the "Type 1" column;
# Get the aggreagated values (totals) of the each numeric columns uisng the "sum()" function after the "groupby()" func;
data_csv.groupby("Type 1").sum()

              #    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Total  Total2
Type 1
Bug       23080  3925    4897     4880     3717     4471   4256  26146   26146
Dark      14302  2071    2740     2177     2314     2155   2361  13818   13818
Dragon    15180  2666    3588     2764     3099     2843   2657  17617   17617
Electric  15994  2631    3040     2917     3961     3243   3718  19510   19510
Fairy      7642  1260    1046     1117     1335     1440    826   7024    7024
Fighting   9824  1886    2613     1780     1434     1747   1784  11244   11244
Flammer   17025  3635    4408     3524     4627     3755   3871  23820   23820
Flying     2711   283     315      265      377      290    410   1940    1940
Ghost     15568  2062    2361     2598     2539     2447   2059  14066   14066
Grass     24141  4709    5125     4956     5425     4930   4335  29480   29480
Ground    11401  2361    3064     2715     1807     2008   2045  14000   14000
Ice       10165  1728    1746     1714     1861     1831   1523  10403   10403
Normal    31279  7573    7200     5865     5470     6245   7012  39365   39365
Poison     7050  1883    2091     1927     1692     1803   1780  11176   11176
Psychic   21706  4026    4073     3858     5609     4918   4645  27129   27129
Rock      17280  2876    4086     4435     2787     3321   2460  19965   19965
Steel     11957  1761    2503     3412     1823     2177   1492  13168   13168
Water     33946  8071    8305     8170     8379     7898   7388  48211   48211

In [130]:
# Organize the clustered dataframe based on the "Total" column in descending order
data_csv.groupby("Type 1").sum().sort_values("Total", ascending=False)

              #    HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Total  Total2
Type 1
Water     33946  8071    8305     8170     8379     7898   7388  48211   48211
Normal    31279  7573    7200     5865     5470     6245   7012  39365   39365
Grass     24141  4709    5125     4956     5425     4930   4335  29480   29480
Psychic   21706  4026    4073     3858     5609     4918   4645  27129   27129
Bug       23080  3925    4897     4880     3717     4471   4256  26146   26146
Flammer   17025  3635    4408     3524     4627     3755   3871  23820   23820
Rock      17280  2876    4086     4435     2787     3321   2460  19965   19965
Electric  15994  2631    3040     2917     3961     3243   3718  19510   19510
Dragon    15180  2666    3588     2764     3099     2843   2657  17617   17617
Ghost     15568  2062    2361     2598     2539     2447   2059  14066   14066
Ground    11401  2361    3064     2715     1807     2008   2045  14000   14000
Dark      14302  2071    2740     2177     2314     2155   2361  13818   13818
Steel     11957  1761    2503     3412     1823     2177   1492  13168   13168
Fighting   9824  1886    2613     1780     1434     1747   1784  11244   11244
Poison     7050  1883    2091     1927     1692     1803   1780  11176   11176
Ice       10165  1728    1746     1714     1861     1831   1523  10403   10403
Fairy      7642  1260    1046     1117     1335     1440    826   7024    7024
Flying     2711   283     315      265      377      290    410   1940    1940

In [135]:
# Display how many non-NaN values avaialable after clustering/grouping-by based on the "Type 1" column;
# The non-NaN values will be silently ignored for counting
data_csv.groupby("Type 1").count()

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2
Type 1,,,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27,27,27
Flammer,52,52,24,52,52,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112,112,112

In [142]:
data_csv["Count"] = 1 # Create a new column "Count"; store the totals of 

data_csv.groupby("Type 1").count() # simultaneously counting the values available in each columns & assigning them into the "Count" column

,#,Name,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2,Count
Type 1,,,,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27,27,27,27
Flammer,52,52,24,52,52,52,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32,32,32,32
Grass,70,70,37,70,70,70,70,70,70,70,70,70,70,70
Ground,32,32,19,32,32,32,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98,98,98,98
Poison,28,28,13,28,28,28,28,28,28,28,28,28,28,28
Psychic,57,57,19,57,57,57,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112,112,112,112

In [148]:
# simultaneously counting the values available in each columns & assigning them into the "Count" column;
# later, display only the "Count" column as a Series
data_csv.groupby("Type 1").count()["Count"]

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Flammer      52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: Count, dtype: int64

In [149]:
data_csv

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total,Total2,Count
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318,318,1
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405,405,1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,TEST VALUE,TEST VALUE,525,525,1
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,TEST VALUE,TEST VALUE,625,625,1
4,4,Charmander,Flammer,NaN,39,52,43,60,50,65,1,True,309,309,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,TEST VALUE,TEST VALUE,600,600,1
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,TEST VALUE,TEST VALUE,700,700,1
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,TEST VALUE,TEST VALUE,600,600,1
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,TEST VALUE,TEST VALUE,680,680,1
799,721,Volcanion,Flammer,Water,80,110,120,130,90,70,TEST VALUE,TEST VALUE,600,600,1

### Timestamp ---->  53:26